/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __mavconn_mavlink_msg_container_t_hpp__
#define __mavconn_mavlink_msg_container_t_hpp__

#include <vector>
#include "mavlink_message_t.hpp"

namespace mavconn
{

class mavlink_msg_container_t
{
    public:
        int8_t     link_network_source;
        int8_t     link_component_id;
        mavconn::mavlink_message_t msg;
        int32_t    extended_payload_len;
        std::vector< int8_t > extended_payload;

    public:
        inline int encode(void *buf, int offset, int maxlen) const;
        inline int getEncodedSize() const;
        inline int decode(const void *buf, int offset, int maxlen);
        inline static int64_t getHash();
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static int64_t _computeHash(const __lcm_hash_ptr *p);
};

int mavlink_msg_container_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int mavlink_msg_container_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int mavlink_msg_container_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t mavlink_msg_container_t::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* mavlink_msg_container_t::getTypeName()
{
    return "mavlink_msg_container_t";
}

int mavlink_msg_container_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->link_network_source, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->link_component_id, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->msg._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->extended_payload_len, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->extended_payload[0], this->extended_payload_len);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int mavlink_msg_container_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->link_network_source, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->link_component_id, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->msg._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->extended_payload_len, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->extended_payload.resize(this->extended_payload_len);
    if(this->extended_payload_len) {
        tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->extended_payload[0], this->extended_payload_len);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int mavlink_msg_container_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    enc_size += this->msg._getEncodedSizeNoHash();
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int8_t_encoded_array_size(NULL, this->extended_payload_len);
    return enc_size;
}

int64_t mavlink_msg_container_t::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == mavlink_msg_container_t::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, (void*)mavlink_msg_container_t::getHash };

    int64_t hash = 0x893144dfcd4de92fLL +
         mavconn::mavlink_message_t::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
