/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _rgbd_camera_image_message_t_h
#define _rgbd_camera_image_message_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _rgbd_camera_image_message_t rgbd_camera_image_message_t;
struct _rgbd_camera_image_message_t
{
    int64_t    utime;
    char*      camera_name;
    float      camera_params[4];
    int16_t    image_width;
    int16_t    image_height;
    int64_t    rgb_data_length;
    int8_t     *rgb_data;
    int64_t    depth_data_length;
    int8_t     *depth_data;
    double     camera_pose[6];
};
 
rgbd_camera_image_message_t   *rgbd_camera_image_message_t_copy(const rgbd_camera_image_message_t *p);
void rgbd_camera_image_message_t_destroy(rgbd_camera_image_message_t *p);

typedef struct _rgbd_camera_image_message_t_subscription_t rgbd_camera_image_message_t_subscription_t;
typedef void(*rgbd_camera_image_message_t_handler_t)(const lcm_recv_buf_t *rbuf, 
             const char *channel, const rgbd_camera_image_message_t *msg, void *user);

int rgbd_camera_image_message_t_publish(lcm_t *lcm, const char *channel, const rgbd_camera_image_message_t *p);
rgbd_camera_image_message_t_subscription_t* rgbd_camera_image_message_t_subscribe(lcm_t *lcm, const char *channel, rgbd_camera_image_message_t_handler_t f, void *userdata);
int rgbd_camera_image_message_t_unsubscribe(lcm_t *lcm, rgbd_camera_image_message_t_subscription_t* hid);

int  rgbd_camera_image_message_t_encode(void *buf, int offset, int maxlen, const rgbd_camera_image_message_t *p);
int  rgbd_camera_image_message_t_decode(const void *buf, int offset, int maxlen, rgbd_camera_image_message_t *p);
int  rgbd_camera_image_message_t_decode_cleanup(rgbd_camera_image_message_t *p);
int  rgbd_camera_image_message_t_encoded_size(const rgbd_camera_image_message_t *p);

// LCM support functions. Users should not call these
int64_t __rgbd_camera_image_message_t_get_hash(void);
int64_t __rgbd_camera_image_message_t_hash_recursive(const __lcm_hash_ptr *p);
int     __rgbd_camera_image_message_t_encode_array(void *buf, int offset, int maxlen, const rgbd_camera_image_message_t *p, int elements);
int     __rgbd_camera_image_message_t_decode_array(const void *buf, int offset, int maxlen, rgbd_camera_image_message_t *p, int elements);
int     __rgbd_camera_image_message_t_decode_array_cleanup(rgbd_camera_image_message_t *p, int elements);
int     __rgbd_camera_image_message_t_encoded_array_size(const rgbd_camera_image_message_t *p, int elements);
int     __rgbd_camera_image_message_t_clone_array(const rgbd_camera_image_message_t *p, rgbd_camera_image_message_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
