struct dds_gl_overlay_message_t
{
    string<255> name;
    char coordinate_frame_type;
    double origin_x;
    double origin_y;
    double origin_z;
    long long length;
    sequence<char,8388608> data;
};
